openapi: 3.0.1
info:
  title: Star Wars
  description: ''
  version: ''
servers:
  - url: https://apim-dev-cu-hol-sf-01.azure-api.net/sw
paths:
  /people/:
    get:
      summary: Get People
      operationId: get-people
      responses:
        '200':
          description: 
  '/people/{id}/':
    get:
      summary: Get People By Id
      operationId: get-people-by-id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
  /favorite:
    get:
      summary: Get Favorite Person
      operationId: get-favorite-person
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]